### ISSUE TITLE
Sequential project member download results in error - sometimes

### ISSUE THREAD

**Issue by CuriousF0x** [OpenHumans/open-humans-api#105]
## Description

We wanted to download the files for each of our TeQfor1-project's members via the CLI call

```
ohproj-download --master-token OH_TOKEN --directory INPUT_PATH -m SOME_ID
ohproj-download --master-token OH_TOKEN --directory INPUT_PATH -m SOME_OTHER_ID
ohproj-download --master-token OH_TOKEN --directory INPUT_PATH -m YET_SOME_OTHER_ID
....
```

Overall, approx 30 calls are made. These calls are executed automatically via a CI/CD pipeline running on a dedicated gitlab runner VM.
During the procedure the execution stops at different points in time(once after 40 min, then after 90 min) . However, not every time - that's the good part. At the third attempt it executed smoothly (I did not changed configuration or sth) - took approx. 170 min. 

Here are the stacktraces I encountered

```
Traceback (most recent call last):
  File "/usr/local/bin/ohproj-download", line 8, in <module>
    sys.exit(download_cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ohapi/command_line.py", line 65, in download_cli
    return download(directory, master_token, member, access_token, source,
  File "/usr/local/lib/python3.8/dist-packages/ohapi/command_line.py", line 132, in download
    project.download_member_shared(
  File "/usr/local/lib/python3.8/dist-packages/ohapi/projects.py", line 135, in download_member_shared
    download_file(download_url=file_data[basename]['download_url'],
  File "/usr/local/lib/python3.8/dist-packages/ohapi/utils_fs.py", line 481, in download_file
    size = int(response.headers['Content-Length'])
  File "/usr/local/lib/python3.8/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```
and during another attempt

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/ohproj-download", line 8, in <module>
    sys.exit(download_cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ohapi/command_line.py", line 65, in download_cli
    return download(directory, master_token, member, access_token, source,
  File "/usr/local/lib/python3.8/dist-packages/ohapi/command_line.py", line 132, in download
    project.download_member_shared(
  File "/usr/local/lib/python3.8/dist-packages/ohapi/projects.py", line 135, in download_member_shared
    download_file(download_url=file_data[basename]['download_url'],
  File "/usr/local/lib/python3.8/dist-packages/ohapi/utils_fs.py", line 480, in download_file
    response = requests.get(download_url, stream=True)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
Maybe it was just a hiccup of the servers.... I triggered the pipeline just now to have a look if it produces the stacktraces again - or if it runs smoothly.

## Related Issue(s)
Relates to #104 - this was the workaround suggested by @gedankenstuecke

**Comment by gedankenstuecke** [comment]
Given those two different errors I'm tempted to say that it's a server hiccup on either our side or that the VM that runs the download might have lost connection. Maybe adding some error handling to the sequential calls would already be a hot fix on your end? :)

**Comment by CuriousF0x** [comment]
`Maybe adding some error handling to the sequential calls` 

True :+1: 

For the records, the export I triggered earlier this afternoon was fine as well. 50:50 rate of success now. ;)
Shall we close this issue here and take it as a "glitch in the matrix"?

**Comment by gedankenstuecke** [comment]
Yep, let's do that, as it's really hard to debug this when it's unclear on which side things time out :-)
