### ISSUE TITLE
Data download gets an incorrectly written error

### ISSUE THREAD

**Issue by danamlewis** [OpenHumans/open-humans-api#86]
As discussed with @madprime, downloading data yielded an incorrectly written error.

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ohproj-download", line 9, in <module>
    load_entry_point('open-humans-api==0.1.3', 'console_scripts', 'ohproj-download')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/ohapi/command_line.py", line 54, in download
    excludelist = read_id_list(excludelist)
  File "/Library/Python/2.7/site-packages/ohapi/utils.py", line 291, in read_id_list
    raise('Each line in whitelist or blacklist is expected '
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```
this isn't raising the error correctly: https://github.com/OpenHumans/open-humans-api/blob/master/ohapi/utils_fs.py#L507

**Comment by danamlewis** [comment]
(Related to leading zero's being removed by excel when I opened a project metadata; I then copy/pasted into a .txt. Adding the missing leading zero's to usernames resolved the root issue)
